blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/mochi-sann/mi-deck/blob/main/readme.md
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®åŸºæœ¬æƒ…å ±ã¨ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—æ–¹æ³•
  - name: ğŸ’¬ Discussions
    url: https://github.com/mochi-sann/mi-deck/discussions
    about: ä¸€èˆ¬çš„ãªè³ªå•ã‚„è­°è«–ã¯ã“ã¡ã‚‰