name: bundle size check
on:
  pull_request:
permissions: write-all
jobs:
  build-head:
    name: Build head
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Build
        run: pnpm run build --filter=@mi-deck/front
      - name: Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: head-stats
          path: ./apps/front/dist/stats.json
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Build
        run: pnpm run build --filter=@mi-deck/front
      - name: Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: base-stats
          path: ./apps/front/dist/stats.json
  compare:
    name: Compare bundle size
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    permissions:
      pull-requests: write
    steps:
      - name: Download stats.json files
        uses: actions/download-artifact@v4
      - name: Compare bundle size
        uses: wojtekmaj/vite-compare-bundle-size@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/stats.json
          base-stats-json-path: ./base-stats/stats.json
